-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE SALES_DATE >= TO_DATE('2022-01-01', 'YYYY-MM-DD') 
AND SALES_DATE < TO_DATE('2022-02-01', 'YYYY-MM-DD')
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY
ORDER BY B.AUTHOR_ID ASC, CATEGORY DESC;