SELECT 
    EXTRACT(YEAR FROM O.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT O.USER_ID) / (
            SELECT COUNT(*)
            FROM USER_INFO
            WHERE EXTRACT(YEAR FROM JOINED) = 2021
        ), 1
    ) AS PURCHASED_RATIO
FROM 
    ONLINE_SALE O
WHERE
    O.USER_ID IN (
        SELECT USER_ID
        FROM USER_INFO
        WHERE EXTRACT(YEAR FROM JOINED) = 2021
    )
GROUP BY
    EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
ORDER BY
    YEAR, MONTH