SELECT
    NAME,
    DATETIME
FROM  (
    SELECT
        I.NAME,
        I.DATETIME
    FROM
        ANIMAL_INS I
    LEFT OUTER JOIN
        ANIMAL_OUTS O
    ON
        O.ANIMAL_ID = I.ANIMAL_ID
    WHERE
        O.ANIMAL_ID IS NULL
    ORDER BY
        DATETIME ASC
)
WHERE ROWNUM <= 3