SELECT
    SUM(SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, POSITION, EMAIL
FROM
    HR_EMPLOYEES E
JOIN
    HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
JOIN
    HR_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY
    E.EMP_NO
ORDER BY
    SUM(SCORE) DESC
LIMIT 1